export const productData = [
    {
        productId: "101",
        image: "https://assets.turbologo.com/blog/en/2021/09/10093610/photo-camera-958x575.png",
        title: "Nickon S39M, 524GB, -Grid Pixel advance lens upto 5MPX",
        discount: "45",
        rating: "4.1",
        reviewCount: "12,342",
        tags : {
            freeDelivery: true,
            bestSaller: true,
            bestPrice: true,
        },
        price: "34,246",
    },{
        productId: "102",
        image: "https://img.freepik.com/free-psd/gadget-concept-instagram-stories-template_23-2148626922.jpg?semt=ais_hybrid&w=740",
        title: "Nickon S39M, 524GB, -Grid Pixel advance lens upto 5MPX",
        discount: "45",
        rating: "4.1",
        reviewCount: "12,342",
        tags : {
            freeDelivery: true,
            bestSaller: true,
            bestPrice: true,
        },
        price: "34,246",
    },{
        productId: "103",
        image: "https://assets.turbologo.com/blog/en/2021/09/10093610/photo-camera-958x575.png",
        title: "Nickon S39M, 524GB, -Grid Pixel advance lens upto 5MPX",
        discount: "45",
        rating: "4.1",
        reviewCount: "12,342",
        tags : {
            freeDelivery: true,
            bestSaller: true,
            bestPrice: true,
        },
        price: "34,246",
    },{
        productId: "104",
        image: "https://assets.turbologo.com/blog/en/2021/09/10093610/photo-camera-958x575.png",
        title: "Nickon S39M, 524GB, -Grid Pixel advance lens upto 5MPX",
        discount: "45",
        rating: "4.1",
        reviewCount: "12,342",
        tags : {
            freeDelivery: true,
            bestSaller: true,
            bestPrice: true,
        },
        price: "34,246",
    },{
        productId: "105",
        image: "https://assets.turbologo.com/blog/en/2021/09/10093610/photo-camera-958x575.png",
        title: "Nickon S39M, 524GB, -Grid Pixel advance lens upto 5MPX",
        discount: "45",
        rating: "4.1",
        reviewCount: "12,342",
        tags : {
            freeDelivery: true,
            bestSaller: true,
            bestPrice: true,
        },
        price: "34,246",
    },{
        productId: "106",
        image: "https://assets.turbologo.com/blog/en/2021/09/10093610/photo-camera-958x575.png",
        title: "Nickon S39M, 524GB, -Grid Pixel advance lens upto 5MPX",
        discount: "45",
        rating: "4.1",
        reviewCount: "12,342",
        tags : {
            freeDelivery: true,
            bestSaller: true,
            bestPrice: true,
        },
        price: "34,246",
    },{
        productId: "107",
        image: "https://assets.turbologo.com/blog/en/2021/09/10093610/photo-camera-958x575.png",
        title: "Nickon S39M, 524GB, -Grid Pixel advance lens upto 5MPX",
        discount: "45",
        rating: "4.1",
        reviewCount: "12,342",
        tags : {
            freeDelivery: true,
            bestSaller: true,
            bestPrice: true,
        },
        price: "34,246",
    },{
        productId: "108",
        image: "https://assets.turbologo.com/blog/en/2021/09/10093610/photo-camera-958x575.png",
        title: "Nickon S39M, 524GB, -Grid Pixel advance lens upto 5MPX",
        discount: "45",
        rating: "4.1",
        reviewCount: "12,342",
        tags : {
            freeDelivery: true,
            bestSaller: true,
            bestPrice: true,
        },
        price: "34,246",
    },{
        productId: "109",
        image: "https://assets.turbologo.com/blog/en/2021/09/10093610/photo-camera-958x575.png",
        title: "Nickon S39M, 524GB, -Grid Pixel advance lens upto 5MPX",
        discount: "45",
        rating: "4.1",
        reviewCount: "12,342",
        tags : {
            freeDelivery: true,
            bestSaller: true,
            bestPrice: true,
        },
        price: "34,246",
    },
    
]